services:
  api-server:
    user: 0:0
    restart: always
    image: moonlightpanel/panel:custom
    build:
      context: .
      dockerfile: ./Moonlight.ApiServer/Dockerfile
    ports:
      - "9069:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MOONLIGHT_DATABASE_HOST=db
      - MOONLIGHT_DATABASE_PORT=5432
      - MOONLIGHT_DATABASE_USERNAME=moonlight
      - MOONLIGHT_DATABASE_PASSWORD=s3cret
      - MOONLIGHT_DATABASE_DATABASE=moonlight
      - MOONLIGHT_PUBLICURL=http://localhost:9069
      - MOONLIGHT_AUTHENTICATION_OAUTH2_ACCESSENDPOINT=http://localhost:8080 # Use this when moonlight is using local oauth2 and a different port as the public url
    volumes:
      - ./data/moonlight:/app/storage
    links:
      - db
    pull_policy: never
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=moonlight
      - POSTGRES_DB=moonlight
      - POSTGRES_PASSWORD=s3cret
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5